version: '3'
services:
  backend:
    build: ./
    container_name: together-list-be
    ports:
      - '8000:8000'
    env_file:
      - .env
  #   depends_on:
  #     - redis

  # redis:
  #   image: 'redis:alpine'
  #   container_name: cache
  #   ports:
  #     - '6379:6379'
# volumes:
#   redis:
#     driver: local
