services:
  backend:
    image: togetherlist-be
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: together-list-be
    ports:
      - '10000:10000'
    env_file:
      - .env
  #   depends_on:
  #     - redis

  # redis:
  #   image: 'redis:alpine'
  #   container_name: cache
  #   ports:
  #     - '6379:6379'
# volumes:
#   redis:
#     driver: local
